services:
  # 1. Configuración del Backend (Web Service)
  - type: web
    name: mi-backend-acs
    env: node
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # 2. Configuración del Frontend (Static Site corregido)
  - type: web
    name: mi-frontend-acs
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: mi-backend-acs
          property: url
